package com.example.musiclog.data.remote

import com.example.musiclog.data.local.PlaylistWithMusic
import com.google.firebase.database.FirebaseDatabase
import com.google.firebase.database.ServerValue
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.tasks.await
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class FirebaseClient @Inject constructor() {
    private val database = FirebaseDatabase.getInstance()
    private val firestore = FirebaseFirestore.getInstance()

    // 💡 1. 핵심 수정: 맹목적 +1 연산을 폐기하고, 로컬 무결성 기반의 절대값 동기화(Self-Healing) 적용
    fun syncArtistPlayCount(artistName: String, uid: String, absolutePlayCount: Int) {
        if (artistName.isBlank() || uid.isBlank()) return

        val baseRef = database.getReference("rankings").child(artistName)
        baseRef.child("totalPlayCount").setValue(ServerValue.increment(1))

        // 누수된 카운트를 무시하고 폰에 저장된 진짜 재생 횟수(16회)로 서버 데이터를 강제 교정
        baseRef.child("listeners").child(uid).setValue(absolutePlayCount)
    }

    // 2. 플레이리스트 클라우드 백업 (업로드)
    suspend fun syncPlaylistsToCloud(uid: String, localPlaylists: List<PlaylistWithMusic>) {
        if (uid.isBlank() || localPlaylists.isEmpty()) return

        val batch = firestore.batch()
        val userPlaylistsRef = firestore.collection("users").document(uid).collection("playlists")

        localPlaylists.forEach { relation ->
            val playlistId = relation.playlist.playlistId
            val docRef = userPlaylistsRef.document(playlistId)

            val playlistData = mapOf(
                "playlistId" to playlistId,
                "name" to relation.playlist.name,
                "coverUri" to relation.playlist.coverUri,
                "isAutoGenerated" to relation.playlist.isAutoGenerated,
                "createdAt" to relation.playlist.createdAt,
                "songs" to relation.songs.map { music ->
                    mapOf(
                        "id" to music.id,
                        "title" to music.title,
                        "artist" to music.artist,
                        "albumArtUrl" to music.albumArtUrl,
                        "customAlbumArtUri" to music.customAlbumArtUri,
                        "playCount" to music.playCount,
                        "lastPlayedTimeStamp" to music.lastPlayedTimeStamp
                    )
                }
            )
            batch.set(docRef, playlistData)
        }
        batch.commit().await()
    }

    // 3. 플레이리스트 클라우드 복원 (다운로드)
    suspend fun fetchPlaylistsFromCloud(uid: String): List<Map<String, Any>> {
        if (uid.isBlank()) return emptyList()
        return try {
            val snapshot = firestore.collection("users").document(uid).collection("playlists").get().await()
            snapshot.documents.mapNotNull { it.data }
        } catch (e: Exception) {
            emptyList()
        }
    }

    // 4. 전체 청취 기록 백업 (업로드)
    suspend fun syncHistoryToCloud(uid: String, localHistory: List<com.example.musiclog.data.local.MusicEntity>) {
        if (uid.isBlank() || localHistory.isEmpty()) return

        val batch = firestore.batch()
        val historyRef = firestore.collection("users").document(uid).collection("history")

        localHistory.forEach { music ->
            val docRef = historyRef.document(music.id)
            val data = mapOf(
                "id" to music.id,
                "title" to music.title,
                "artist" to music.artist,
                "albumArtUrl" to music.albumArtUrl,
                "customAlbumArtUri" to music.customAlbumArtUri,
                "playCount" to music.playCount,
                "lastPlayedTimeStamp" to music.lastPlayedTimeStamp
            )
            batch.set(docRef, data)
        }
        batch.commit().await()
    }

    // 5. 전체 청취 기록 복원 (다운로드)
    suspend fun fetchHistoryFromCloud(uid: String): List<Map<String, Any>> {
        if (uid.isBlank()) return emptyList()
        return try {
            val snapshot = firestore.collection("users").document(uid).collection("history").get().await()
            snapshot.documents.mapNotNull { it.data }
        } catch (e: Exception) {
            emptyList()
        }
    }

    fun incrementUserTotalPlayCount(uid: String, nickname: String) {
        if (uid.isBlank()) return
        val baseRef = database.getReference("users_ranking").child(uid)
        baseRef.child("nickname").setValue(nickname)
        baseRef.child("totalPlayCount").setValue(ServerValue.increment(1))
    }
}