package com.example.musiclog.ui.playlist

import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.MoreVert
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage

// 도메인 구조가 확립되기 전 UI 테스트를 위한 임시 데이터 클래스
data class DummyPlaylist(
    val id: String,
    val title: String,
    val trackCount: Int,
    val coverUri: String?,
    val isAutoGenerated: Boolean
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PlaylistScreen(
    onNavigateToDashboard: () -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    var targetPlaylistIdForArt by remember { mutableStateOf<String?>(null) }

    // 재생목록 대표 이미지 설정을 위한 갤러리 액티비티 호출 컨트랙트
    val galleryLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetContent()
    ) { uri: Uri? ->
        uri?.let { selectedImageUri ->
            targetPlaylistIdForArt?.let { playlistId ->
                try {
                    context.contentResolver.takePersistableUriPermission(
                        selectedImageUri,
                        android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION
                    )
                } catch (e: Exception) {
                    e.printStackTrace()
                }
                // TODO: 뷰모델을 통해 로컬 DB의 재생목록 커버 이미지 경로 업데이트 로직 연동 필요
            }
        }
    }

    // UI 렌더링을 위한 임시 더미 데이터 배열
    val dummyPlaylists = remember {
        listOf(
            DummyPlaylist("1", "좋아요 표시한 음악", 78, null, true),
            DummyPlaylist("2", "E", 57, "https://picsum.photos/seed/2/300/300", false),
            DummyPlaylist("3", "s", 22, "https://picsum.photos/seed/3/300/300", false)
        )
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("재생목록") },
                navigationIcon = {
                    IconButton(onClick = onNavigateToDashboard) {
                        Icon(imageVector = Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "뒤로가기")
                    }
                }
            )
        },
        floatingActionButton = {
            FloatingActionButton(
                onClick = { /* TODO: 새 재생목록 생성 다이얼로그 호출 로직 */ },
                containerColor = MaterialTheme.colorScheme.primary
            ) {
                Icon(imageVector = Icons.Default.Add, contentDescription = "새 재생목록 생성")
            }
        },
        modifier = modifier
    ) { innerPadding ->
        LazyVerticalGrid(
            columns = GridCells.Fixed(2),
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(horizontal = 16.dp),
            contentPadding = PaddingValues(bottom = 80.dp),
            horizontalArrangement = Arrangement.spacedBy(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            items(dummyPlaylists) { playlist ->
                PlaylistItemCard(
                    playlist = playlist,
                    onEditImageClick = {
                        targetPlaylistIdForArt = playlist.id
                        galleryLauncher.launch("image/*")
                    }
                )
            }
        }
    }
}

@Composable
fun PlaylistItemCard(
    playlist: DummyPlaylist,
    onEditImageClick: () -> Unit
) {
    var expanded by remember { mutableStateOf(false) }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { /* TODO: 재생목록 상세 화면 진입 라우팅 */ },
        horizontalAlignment = Alignment.Start
    ) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .aspectRatio(1f)
                .clip(RoundedCornerShape(8.dp))
                .background(MaterialTheme.colorScheme.surfaceVariant)
        ) {
            // 재생목록 커버 이미지
            if (playlist.coverUri != null) {
                AsyncImage(
                    model = playlist.coverUri,
                    contentDescription = null,
                    modifier = Modifier.fillMaxSize(),
                    contentScale = ContentScale.Crop
                )
            } else {
                // 커버 이미지가 없을 경우 대체 UI
                Icon(
                    imageVector = Icons.Default.Add,
                    contentDescription = null,
                    modifier = Modifier
                        .size(48.dp)
                        .align(Alignment.Center),
                    tint = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            // 우측 상단 3점 메뉴 (Kebab Menu)
            Box(
                modifier = Modifier
                    .align(Alignment.TopEnd)
                    .padding(4.dp)
            ) {
                IconButton(
                    onClick = { expanded = true },
                    modifier = Modifier
                        .background(
                            color = MaterialTheme.colorScheme.surface.copy(alpha = 0.7f),
                            shape = RoundedCornerShape(50)
                        )
                        .size(32.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.MoreVert,
                        contentDescription = "재생목록 옵션",
                        modifier = Modifier.size(20.dp)
                    )
                }

                DropdownMenu(
                    expanded = expanded,
                    onDismissRequest = { expanded = false }
                ) {
                    DropdownMenuItem(
                        text = { Text("재생목록 수정") },
                        onClick = {
                            expanded = false
                            // TODO: 이름 수정 등 다이얼로그 호출
                        }
                    )
                    DropdownMenuItem(
                        text = { Text("대표 이미지 설정") },
                        onClick = {
                            expanded = false
                            onEditImageClick()
                        }
                    )
                    if (!playlist.isAutoGenerated) {
                        DropdownMenuItem(
                            text = { Text("재생목록 삭제", color = MaterialTheme.colorScheme.error) },
                            onClick = {
                                expanded = false
                                // TODO: 삭제 확인 다이얼로그 호출
                            }
                        )
                    }
                }
            }
        }

        Spacer(modifier = Modifier.height(8.dp))

        Text(
            text = playlist.title,
            style = MaterialTheme.typography.titleMedium,
            maxLines = 1
        )
        Text(
            text = "트랙 ${playlist.trackCount}개",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.secondary
        )
    }
}