package com.example.musiclog.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.musiclog.data.local.PlaylistDao
import com.example.musiclog.data.local.PlaylistEntity
import com.example.musiclog.data.local.PlaylistWithMusic
import com.example.musiclog.data.mapper.toDomain // 💡 확장 변환 함수 임포트
import com.example.musiclog.ui.playlist.DummyPlaylist
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.util.UUID
import javax.inject.Inject

data class PlaylistDetailUiState(
    val id: String,
    val title: String,
    val coverUri: String?,
    val songs: List<com.example.musiclog.domain.model.Music>
)

@HiltViewModel
class PlaylistViewModel @Inject constructor(
    private val playlistDao: PlaylistDao
) : ViewModel() {

    @Inject
    lateinit var musicDao: com.example.musiclog.data.local.MusicDao

    val playlists: StateFlow<List<DummyPlaylist>> = playlistDao.getPlaylistsWithMusic()
        .map { list ->
            list.map { relation ->
                DummyPlaylist(
                    id = relation.playlist.playlistId,
                    title = relation.playlist.name,
                    trackCount = relation.songs.size,
                    coverUri = relation.playlist.coverUri,
                    isAutoGenerated = relation.playlist.isAutoGenerated
                )
            }
        }
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5000),
            initialValue = emptyList()
        )

    // PlaylistViewModel.kt 내부
    fun getAllMusicLog(): Flow<List<com.example.musiclog.domain.model.Music>> {
        return musicDao.getAllMusic().map { entities ->
            entities.map { entity ->
                val domain = entity.toDomain()
                // 💡 곡 추가 다이얼로그용 스트림 디코딩
                domain.copy(
                    title = android.text.Html.fromHtml(domain.title, android.text.Html.FROM_HTML_MODE_LEGACY).toString(),
                    artist = android.text.Html.fromHtml(domain.artist, android.text.Html.FROM_HTML_MODE_LEGACY).toString()
                )
            }
        }
    }

    fun getPlaylistDetail(playlistId: String): Flow<PlaylistDetailUiState?> {
        return playlistDao.getPlaylistWithMusicById(playlistId).map { relation ->
            relation?.let {
                PlaylistDetailUiState(
                    id = it.playlist.playlistId,
                    title = it.playlist.name,
                    coverUri = it.playlist.coverUri,
                    songs = it.songs.map { entity ->
                        com.example.musiclog.domain.model.Music(
                            id = entity.id,
                            title = entity.title,
                            artist = entity.artist,
                            albumArtUrl = entity.albumArtUrl,
                            customAlbumArtUri = entity.customAlbumArtUri,
                            playCount = entity.playCount,
                            lastPlayedTimeStamp = entity.lastPlayedTimeStamp
                        )
                    }
                )
            }
        }
    }

    fun createPlaylist(name: String, isAutoGenerated: Boolean = false) {
        viewModelScope.launch(Dispatchers.IO) {
            val newPlaylist = PlaylistEntity(
                playlistId = UUID.randomUUID().toString(),
                name = name,
                coverUri = null,
                isAutoGenerated = isAutoGenerated,
                createdAt = System.currentTimeMillis()
            )
            playlistDao.insertPlaylist(newPlaylist)
        }
    }

    fun addMusicToPlaylist(playlistId: String, music: com.example.musiclog.domain.model.Music) {
        viewModelScope.launch(Dispatchers.IO) {
            val musicEntity = com.example.musiclog.data.local.MusicEntity(
                id = music.id,
                title = music.title,
                artist = music.artist,
                albumArtUrl = music.albumArtUrl,
                customAlbumArtUri = music.customAlbumArtUri,
                playCount = music.playCount,
                lastPlayedTimeStamp = music.lastPlayedTimeStamp
            )
            musicDao.insertMusic(musicEntity)

            val crossRef = com.example.musiclog.data.local.PlaylistMusicCrossRef(
                playlistId = playlistId,
                musicId = music.id
            )
            playlistDao.insertPlaylistMusicCrossRef(crossRef)
        }
    }

    fun updatePlaylistCover(playlistId: String, uri: String) {
        viewModelScope.launch {
            playlistDao.updatePlaylistCover(playlistId, uri)
        }
    }

    fun deletePlaylist(playlistId: String) {
        viewModelScope.launch {
            playlistDao.deletePlaylist(playlistId)
        }
    }

    fun removeMusicFromPlaylist(playlistId: String, musicId: String) {
        viewModelScope.launch {
            playlistDao.deletePlaylistMusicCrossRef(playlistId, musicId)
        }
    }
}