package com.example.musiclog.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.musiclog.data.local.PlaylistDao
import com.example.musiclog.data.local.PlaylistEntity
import com.example.musiclog.ui.playlist.DummyPlaylist // 임시 도메인 모델 재활용 또는 정식 도메인 모델 연동
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.util.UUID
import javax.inject.Inject

@HiltViewModel
class PlaylistViewModel @Inject constructor(
    private val playlistDao: PlaylistDao
) : ViewModel() {

    // 로컬 DB의 재생목록 스트림을 UI 상태로 변환
    val playlists: StateFlow<List<DummyPlaylist>> = playlistDao.getPlaylistsWithMusic()
        .map { list ->
            list.map { relation ->
                DummyPlaylist(
                    id = relation.playlist.playlistId,
                    title = relation.playlist.name,
                    trackCount = relation.songs.size, // 교차 참조된 곡의 개수 산출
                    coverUri = relation.playlist.coverUri,
                    isAutoGenerated = relation.playlist.isAutoGenerated
                )
            }
        }
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5000),
            initialValue = emptyList()
        )

    fun createPlaylist(name: String, isAutoGenerated: Boolean = false) {
        viewModelScope.launch {
            val newPlaylist = PlaylistEntity(
                playlistId = UUID.randomUUID().toString(),
                name = name,
                coverUri = null,
                isAutoGenerated = isAutoGenerated,
                createdAt = System.currentTimeMillis()
            )
            playlistDao.insertPlaylist(newPlaylist)
        }
    }

    fun updatePlaylistCover(playlistId: String, uri: String) {
        viewModelScope.launch {
            playlistDao.updatePlaylistCover(playlistId, uri)
        }
    }

    fun deletePlaylist(playlistId: String) {
        viewModelScope.launch {
            playlistDao.deletePlaylist(playlistId)
        }
    }
}