package com.example.musiclog.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "playlist_table")
data class PlaylistEntity(
    @PrimaryKey val playlistId: String,
    val name: String,
    val coverUri: String?,
    val isAutoGenerated: Boolean,
    val createdAt: Long
)